# Generated by Django 6.0.2 on 2026-02-21 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_vehicle_id_and_more'),
        ('operations', '0001_initial'),
        ('trips', '0002_remove_trip_created_at_remove_trip_end_odometer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fuellog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='id',
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='logged_by',
            field=models.ForeignKey(db_column='logged_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='logged_by',
            field=models.ForeignKey(db_column='logged_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='next_service_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='odometer_at_fill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='trip',
            field=models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='odometer_at_service',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='service_type',
            field=models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_change', 'Tire Change'), ('brake_service', 'Brake Service'), ('engine_repair', 'Engine Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle'),
        ),
        migrations.AlterModelTable(
            name='fuellog',
            table='fuel_logs',
        ),
        migrations.AlterModelTable(
            name='maintenancelog',
            table='maintenance_logs',
        ),
    ]
