# Generated by Django 6.0.2 on 2026-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=20)),
                ('license_expiry_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_trip', 'On Trip'), ('suspended', 'Suspended')], default='on_duty', max_length=15)),
                ('safety_score', models.IntegerField(default=100)),
                ('trips_completed', models.IntegerField(default=0)),
                ('trips_cancelled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
