# Generated by Django 6.0.2 on 2026-02-21 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_duty", "On Duty"),
                            ("off_duty", "Off Duty"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="off_duty",
                        max_length=15,
                    ),
                ),
                (
                    "safety_score",
                    models.DecimalField(decimal_places=1, default=100.0, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
