# Generated by Django 6.0.2 on 2026-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_full_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("dispatcher", "Dispatcher"),
                    ("safety_officer", "Safety Officer"),
                    ("finance", "Finance"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
    ]
