# Generated by Django 6.0.2 on 2026-02-21 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_load_capacity_kg',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], default='truck', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
