# Generated by Django 6.0.2 on 2026-02-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("oil_change", "Oil Change"),
                            ("tire_rotation", "Tire Rotation"),
                            ("brake_service", "Brake Service"),
                            ("engine_repair", "Engine Repair"),
                            ("transmission", "Transmission"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_in", models.DateField()),
                ("date_out", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_logs",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_in"],
            },
        ),
    ]
