# Generated by Django 6.0.2 on 2026-02-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
        ),
    ]
