# Generated by Django 6.0.2 on 2026-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("bus", "Bus"),
                        ],
                        max_length=10,
                    ),
                ),
                ("capacity_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_trip", "On Trip"),
                            ("in_shop", "In Shop"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=15,
                    ),
                ),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
